language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- '0.8'
- 'iojs'
- 'iojs-v1.8.1'
matrix:
  fast_finish: true
sudo: false
env:
- TZ=Etc/UTC
- TZ=America/Los_Angeles
before_install:
- node test/scripts/npm.js
- npm install -g grunt-cli
- date
script:
- grunt ci
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: scvV1vsf/S4OgeXjKysHViN4cVjyZQYo+nzl0UY9DsDeYCVoEijnTN4zR46eC7CVCXiUL13kc8VSqmk0w/9ZHNnj37fGE9wfRAuMNGmqIzi8in4ZTaGip/OxKtjW3mmWnst7HyR92C6mo0HtBa1BFa2jw8fhi8TmSbktTvW7UIo=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack
