# Site settings
title: steeplejack
description: > #
  steeplejack is a scaffolding framework for node.js/io.js that adds
  awesomity to your projects - Dependency Injection, data models and collections,
  URL routing and class inheritance for grown-ups - all out of the box.
baseurl: ""
url: "http://steeplejack.info"

# Build settings
markdown: kramdown

nav:
    -
        name: "Home"
        url: "/"
    -
        name: "Documentation"
        url: "/docs/"

docs:
    -
        title: "Getting Started"
        items:
            -
                name: "Installation"
                url: "/docs/getting-started/"
            -
                name: "Your First App"
                url: "/docs/getting-started/your-first-app/"
            -
                name: "Routing"
                url: "/docs/getting-started/routing/"
            -
                name: "Models and Collections"
                url: "/docs/getting-started/models-and-collections/"
            -
                name: "Running Your App"
                url: "/docs/getting-started/running-your-app/"
            -
                name: "Config"
                url: "/docs/getting-started/config/"
    -
        title: "API Reference"
        items:
            -
                name: "Collections"
                url: "/docs/api/collections/"
            -
                name: "Dependency Injection"
                url: "/docs/api/dependency-injection/"
            -
                name: "Errors"
                url: "/docs/api/errors/"
            -
                name: "HTTP"
                url: "/docs/api/http"
            -
                name: "Inheritance"
                url: "/docs/api/inheritance/"
            -
                name: "Logging"
                url: "/docs/api/logging/"
            -
                name: "Models"
                url: "/docs/api/models/"
            -
                name: "Router"
                url: "/docs/api/router/"
    -
        title: "Plugins"
        items:
            -
                name: "HTTP Strategies"
                url: "/docs/plugins/http-strategies/"
            -
                name: "Logging Strategies"
                url: "/docs/plugins/logginghttp-strategies.md-strategies/"
